name: flutter_ui_auth
description: "A customizable login screen with animations for Flutter applications."
version: 1.0.0

homepage: https://www.cod-e-codes.com
repository: https://github.com/cod-e-codes/flutter_ui_auth

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_animations: ^1.1.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
